name: Main

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - uses: actions/checkout@v2

    - name: Build and test
      run: |
        ./ci.sh
